### ISSUE TITLE
fails to flash oem

### ISSUE THREAD

**Issue by nieldk** [sonyxperiadev/device-sony-dora#14]
I successfully build and flashed boot, system and userdata. for Android Oreo (8.0)
However, when trying to flash oem partition it fails

```
# fastboot flash oem SW_binaries_for_Xperia_AOSP_O_MR0_4.4_v02_tone.img 
target reported max download size of 268435456 bytes
sending 'oem' (212596 KB)...
OKAY [  8.267s]
writing 'oem'...
FAILED (remote: Command not allowed)
finished. total time: 8.281s
```

I have installed the latest available FW using Emma (41.2.A.7.65) and bootloader is unlocked, USB debugging enabled.

I have also tryied dd'ing the (adb) Xperia_AOSP_O_MR0_4.4_v02_tone.img to /dev/block/mmcblk0p42 which is the oem partition. But this is also not allowed (I am root).

Booting to recovery tells me system is Android Oreo (8.0)

Any suggestions ?

**Comment by jerpelea** [comment]
please use https://github.com/sonyxperiadev/bug_tracker for future issues
